import { logo } from "../src/assets/images/images";

export const UserDummyJobData = [
  {
    id: "job-12345",
    company: {
      name: "Tech Innovators Inc.",
      website: "www.techinnovators.com",
      logo: logo,
      logoBackground: "#1E90FF",
    },
    postedAt: "2025-04-10",
    contract: "Full Time",
    position: "Senior Software Engineer",
    location: "San Francisco, CA (Remote Available)",
    salary: "$120,000 - $150,000",
    description: "We are looking for a Senior Software Engineer to join our dynamic team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers.",
    shortDescription: "Build enterprise applications and mentor junior developers in a collaborative environment.",
    qualifications: {
      content: "Qualifications & Required Skills:",
      items: [
        "5+ years of experience in software development",
        "Proficiency in JavaScript, React, and Node.js",
        "Strong understanding of RESTful APIs and web services",
        "Experience with cloud platforms such as AWS or Azure",
        "Bachelor's degree in Computer Science or related field (or equivalent experience)",
        "Excellent problem-solving skills and attention to detail",
        "Strong communication and teamwork abilities",
      ],
    },
    responsibilities: {
      content: "Responsibilities:",
      items: [
        "Designing and developing high-quality software applications",
        "Collaborating with product managers and designers",
        "Writing clean, maintainable code and conducting code reviews",
        "Mentoring junior developers",
        "Implementing security best practices and performance optimizations",
        "Participating in architectural discussions and planning",
      ],
    },
    benefits: {
      content: "Benefits:",
      items: [
        "Competitive salary",
        "Health insurance",
        "Flexible working hours",
        "Remote work options",
        "Professional development opportunities",
        "401(k) matching program",
        "Generous paid time off",
      ],
    },
    status: "active",
    applicants: 0,
    applicationDeadline: "2025-05-30",
    AppliedJobs: [],
    applyUrl: "https://techinnovators.com/careers/apply/senior-software-engineer"
  },
  {
    id: "job-67890",
    company: {
      name: "Innovative Solutions Ltd.",
      website: "www.innovativesolutions.com",
      logo: logo,
      logoBackground: "#FF6347",
    },
    postedAt: "2025-04-05",
    contract: "Part Time",
    position: "Frontend Developer",
    location: "New York, NY (Remote)",
    salary: "$70,000 - $90,000",
    description: "We are seeking a talented Frontend Developer to join our team. You will be responsible for building responsive user interfaces, ensuring the best possible user experience.",
    shortDescription: "Create responsive user interfaces with modern web technologies for optimal user experience.",
    qualifications: {
      content: "Qualifications & Required Skills:",
      items: [
        "3+ years of experience in frontend development",
        "Proficiency in HTML, CSS, and JavaScript/TypeScript",
        "Experience with React or Vue.js frameworks",
        "Strong understanding of responsive design principles",
        "Familiarity with version control systems like Git",
        "Bachelor's degree in Computer Science or related field (or equivalent experience)",
        "Portfolio demonstrating frontend development skills",
      ],
    },
    responsibilities: {
      content: "Responsibilities:",
      items: [
        "Developing responsive user interfaces",
        "Collaborating with designers and backend developers",
        "Optimizing applications for maximum speed and scalability",
        "Writing clean, maintainable code",
        "Implementing UI/UX designs with precision and attention to detail",
        "Testing and debugging across multiple browsers and devices",
      ],
    },
    benefits: {
      content: "Benefits:",
      items: [
        "Competitive hourly rate",
        "Flexible schedule",
        "Remote work options",
        "Professional development stipend",
        "Collaborative team environment",
      ],
    },
    status: "closed",
    applicants: 5,
    applicationDeadline: "2025-05-15",
    AppliedJobs: [],
    applyUrl: "https://innovativesolutions.com/jobs/frontend-developer"
  },
  {
    id: "job-11223",
    company: {
      name: "NextGen Tech",
      website: "www.nextgentech.com",
      logo: logo,
      logoBackground: "#32CD32",
    },
    postedAt: "2025-04-08",
    contract: "Contract",
    position: "Backend Developer",
    location: "Austin, TX (Hybrid)",
    salary: "$90,000 - $120,000",
    description: "Join our team as a Backend Developer responsible for server-side logic, database design, and API development. Help us build scalable solutions for our growing client base.",
    shortDescription: "Develop server-side applications, design databases, and build scalable RESTful APIs.",
    qualifications: {
      content: "Qualifications & Required Skills:",
      items: [
        "4+ years of experience in backend development",
        "Proficiency in Node.js/Express or Python/Django",
        "Strong understanding of RESTful APIs and database design",
        "Experience with SQL and NoSQL databases",
        "Knowledge of authentication, authorization, and security practices",
        "Ability to write efficient, maintainable, and secure code",
        "Bachelor's degree in Computer Science or equivalent experience",
      ],
    },
    responsibilities: {
      content: "Responsibilities:",
      items: [
        "Developing robust server-side applications",
        "Designing and implementing RESTful APIs",
        "Optimizing database performance",
        "Ensuring application security and data protection",
        "Collaborating with frontend developers to integrate services",
        "Implementing effective error handling and logging",
      ],
    },
    benefits: {
      content: "Benefits:",
      items: [
        "Competitive contract rate",
        "Possibility for full-time conversion",
        "Flexible working hours",
        "Modern tech stack",
        "Professional growth opportunities",
      ],
    },
    status: "active",
    applicants: 3,
    applicationDeadline: "2025-05-20",
    AppliedJobs: [
      {
        userId: "user-001",
        appliedAt: "2025-04-15",
        status: "pending",
      },
    ],
    applyUrl: "https://nextgentech.com/careers/backend-developer"
  },
  {
    id: "job-44556",
    company: {
      name: "Future Tech Solutions",
      website: "www.futuretechsolutions.com",
      logo: logo,
      logoBackground: "#FFD700",
    },
    postedAt: "2025-04-12",
    contract: "Full Time",
    position: "DevOps Engineer",
    location: "Seattle, WA (On-site)",
    salary: "$110,000 - $140,000",
    description: "We're looking for a DevOps Engineer to streamline our development and deployment processes. You'll help us build robust CI/CD pipelines and manage cloud infrastructure.",
    shortDescription: "Streamline development workflows and manage cloud infrastructure with modern DevOps practices.",
    qualifications: {
      content: "Qualifications & Required Skills:",
      items: [
        "3+ years of DevOps experience",
        "Strong knowledge of AWS or Azure cloud services",
        "Experience with container orchestration (Docker, Kubernetes)",
        "Proficiency with CI/CD tools (Jenkins, GitHub Actions, etc.)",
        "Experience with infrastructure as code tools (Terraform, CloudFormation)",
        "Linux system administration skills",
        "Understanding of networking and security principles",
      ],
    },
    responsibilities: {
      content: "Responsibilities:",
      items: [
        "Building and maintaining CI/CD pipelines",
        "Managing cloud infrastructure with IaC tools",
        "Monitoring system performance and reliability",
        "Collaborating with development teams to improve deployment processes",
        "Implementing security best practices for infrastructure",
        "Automating routine operations and tasks",
      ],
    },
    benefits: {
      content: "Benefits:",
      items: [
        "Competitive salary",
        "Health and dental insurance",
        "401(k) with company match",
        "Professional development budget",
        "Wellness program",
        "Generous paid time off",
      ],
    },
    status: "active",
    applicants: 2,
    applicationDeadline: "2025-06-01",
    AppliedJobs: [
      {
        userId: "user-002",
        appliedAt: "2025-04-17",
        status: "interview",
      },
    ],
    applyUrl: "https://futuretechsolutions.com/careers/devops-engineer"
  },
];